[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true

[programs.localnet]
shellwork = "EgaRMf8t5gnqEXa37xW9BYxgEiSmTsF2FkNfxr2kbyuh"

[programs.devnet]
shellwork = "EgaRMf8t5gnqEXa37xW9BYxgEiSmTsF2FkNfxr2kbyuh"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "SHELLWORK_LIVE=1 npm test"
